---
title: "Example: R in RStudio"
date: "Last knitted `r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: inline
---

> Click into a code cell (the gray blocks below) to select or edit it. To run a selected code cell, hit `Ctrl`+`Shift`+`Enter` (Windows & Linux) / `Command`+`Shift`+`Enter` (MacOS). Make sure that each code cell runs successfully before you move on to the next one.

# $\LaTeX$ Math

This is just markdown that can include latex math.

$$
\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}
$$

# System Info

```{r}
# session info
sessionInfo()
```


# Custom Function

```{r}
# custom function from scripts/functions.R
source(file.path("scripts", "functions.R"))
test_add(2,5)
```

# Data

```{r, message = FALSE}
# create dataset using dplyr
library(dplyr)
curve <- 
  tibble(
    t = seq(0, 2, by = 0.01),
    y = 1 + sin(2 * pi * t)
  ) 
curve
```

# Plot

```{r, fig.width = 8, fig.height = 6}
# plot using ggplot
library(ggplot2)
curve %>% 
  ggplot() + 
  aes(t, y) +
  geom_line()
```

