---
title: "Week 1 Answer Key"
subtitle: "Avogadro's Law"
author: "Stephanie Plaza-Torres"
date: "Last knitted `r format(Sys.Date(), '%d %b %Y')`"
output: html_document

---
# _Questions and Answers_

### Question 1

Q1. What does $V_{2}$ mean in the context of this equation:
$$
\frac{V_{1}}{n_{1}}\ = \frac{V_{2}}{n_{2}}\ 
$$

### Answer 1

The $V_{2}$ shows the new volume of a gas (in constant pressure and temperature) based on the initial volume and moles of the gas and the final moles of the gas. 

______________________________________________________________________________________

### Question 2

Q2. If you have a 22 liters of oxygen gas that contain 3 mol of oxygen, how many mol of gas would 30 liters of oxygen have? These gases would all be at a constant STP (which is the Standard Temperature and Pressure, $273.15$ $K$ and $10^5$ $Pa$).

### Answer 2

```{r}
calc_mol_list <- list(v1=8.314, n1=80, v2=20)
n2 <- (calc_mol_list$v2*calc_mol_list$n1)/calc_mol_list$v1
cat ("n2 is", n2, "mol")
```

______________________________________________________________________________________

### Question 3

Q3. What happens (to the mol value) if the volume of a gas increases and the temperature and pressure remain constant?

### Answer 3

The mol increases.

______________________________________________________________________________________

### Question 4

Q4. What are the two variables that should remain constant to comply with Avogadro's Law?

### Answer 4

The temperature and the pressure.
